version: "3.9"

services:
  postgres_clinique:
    image: postgres:latest
    container_name: postgres_clinique
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinique
    ports:
      - "5434:5432"   # Host:Container
    volumes:
      - pgdata_clinique:/var/lib/postgresql/data
    networks:
      - clinique_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clinique"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin4_clinique:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_clinique
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8084:80"
    depends_on:
      - postgres_clinique
    networks:
      - clinique_net

  tomcat_clinique:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tomcat_clinique
    ports:
      - "8083:8080"
    depends_on:
      postgres_clinique:
        condition: service_healthy
    networks:
      - clinique_net

volumes:
  pgdata_clinique:

networks:
  clinique_net:
    driver: bridge
