version: "3.9"

services:
  postgres_clinique:
    image: postgres:latest
    container_name: postgres_clinique
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinique
    ports:
      - "5434:5432"
    volumes:
      - pgdata_clinique:/var/lib/postgresql/data
    networks:
      clinique_net:
        aliases:
          - postgres_clinique

  pgadmin4_clinique:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_clinique
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8084:80"
    depends_on:
      - postgres_clinique
    networks:
      clinique_net:
        aliases:
          - pgadmin_clinique

  tomcat_clinique:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tomcat_clinique
    ports:
      - "8083:8080"
    depends_on:
      - postgres_clinique
    networks:
      clinique_net:
        aliases:
          - tomcat_clinique

volumes:
  pgdata_clinique:

networks:
  clinique_net:
    driver: bridge
